//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalParameters", Namespace="http://schemas.datacontract.org/2004/07/TSService")]
    public partial class GlobalParameters : object
    {
        
        private int discovery_timeoutField;
        
        private int eventlog_lookback_daysField;
        
        private int eventlog_timeoutField;
        
        private int id_default_currencyField;
        
        private int id_default_entityField;
        
        private int id_default_locationField;
        
        private int oracle_db_port_fromField;
        
        private int oracle_db_port_toField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int discovery_timeout
        {
            get
            {
                return this.discovery_timeoutField;
            }
            set
            {
                this.discovery_timeoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventlog_lookback_days
        {
            get
            {
                return this.eventlog_lookback_daysField;
            }
            set
            {
                this.eventlog_lookback_daysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventlog_timeout
        {
            get
            {
                return this.eventlog_timeoutField;
            }
            set
            {
                this.eventlog_timeoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_default_currency
        {
            get
            {
                return this.id_default_currencyField;
            }
            set
            {
                this.id_default_currencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_default_entity
        {
            get
            {
                return this.id_default_entityField;
            }
            set
            {
                this.id_default_entityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_default_location
        {
            get
            {
                return this.id_default_locationField;
            }
            set
            {
                this.id_default_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oracle_db_port_from
        {
            get
            {
                return this.oracle_db_port_fromField;
            }
            set
            {
                this.oracle_db_port_fromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oracle_db_port_to
        {
            get
            {
                return this.oracle_db_port_toField;
            }
            set
            {
                this.oracle_db_port_toField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeploymentJSONData", Namespace="http://schemas.datacontract.org/2004/07/TSService")]
    public partial class DeploymentJSONData : object
    {
        
        private string asset_regField;
        
        private string data_classField;
        
        private string data_class_qualifierField;
        
        private string data_jsonField;
        
        private string data_jsonbField;
        
        private int id_deployment_json_dataField;
        
        private int id_entityField;
        
        private int id_locationField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string asset_reg
        {
            get
            {
                return this.asset_regField;
            }
            set
            {
                this.asset_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_class
        {
            get
            {
                return this.data_classField;
            }
            set
            {
                this.data_classField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_class_qualifier
        {
            get
            {
                return this.data_class_qualifierField;
            }
            set
            {
                this.data_class_qualifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_json
        {
            get
            {
                return this.data_jsonField;
            }
            set
            {
                this.data_jsonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_jsonb
        {
            get
            {
                return this.data_jsonbField;
            }
            set
            {
                this.data_jsonbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_deployment_json_data
        {
            get
            {
                return this.id_deployment_json_dataField;
            }
            set
            {
                this.id_deployment_json_dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_entity
        {
            get
            {
                return this.id_entityField;
            }
            set
            {
                this.id_entityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_location
        {
            get
            {
                return this.id_locationField;
            }
            set
            {
                this.id_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGlobalParameter", ReplyAction="http://tempuri.org/IService1/getGlobalParameterResponse")]
        ServiceReference1.GlobalParameters getGlobalParameter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGlobalParameter", ReplyAction="http://tempuri.org/IService1/getGlobalParameterResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GlobalParameters> getGlobalParameterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetAssetDetailsForAPI", ReplyAction="http://tempuri.org/IService1/fnGetAssetDetailsForAPIResponse")]
        string fnGetAssetDetailsForAPI(string strAssetName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetAssetDetailsForAPI", ReplyAction="http://tempuri.org/IService1/fnGetAssetDetailsForAPIResponse")]
        System.Threading.Tasks.Task<string> fnGetAssetDetailsForAPIAsync(string strAssetName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnAddDeploymentJSONData", ReplyAction="http://tempuri.org/IService1/fnAddDeploymentJSONDataResponse")]
        int fnAddDeploymentJSONData(ServiceReference1.DeploymentJSONData DepJSONData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnAddDeploymentJSONData", ReplyAction="http://tempuri.org/IService1/fnAddDeploymentJSONDataResponse")]
        System.Threading.Tasks.Task<int> fnAddDeploymentJSONDataAsync(ServiceReference1.DeploymentJSONData DepJSONData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetAgentTicketManageData", ReplyAction="http://tempuri.org/IService1/fnGetAgentTicketManageDataResponse")]
        string fnGetAgentTicketManageData(string strAgentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetAgentTicketManageData", ReplyAction="http://tempuri.org/IService1/fnGetAgentTicketManageDataResponse")]
        System.Threading.Tasks.Task<string> fnGetAgentTicketManageDataAsync(string strAgentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetTicektDetailsData", ReplyAction="http://tempuri.org/IService1/fnGetTicektDetailsDataResponse")]
        string fnGetTicektDetailsData(string strTicketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnGetTicektDetailsData", ReplyAction="http://tempuri.org/IService1/fnGetTicektDetailsDataResponse")]
        System.Threading.Tasks.Task<string> fnGetTicektDetailsDataAsync(string strTicketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnInsertTicketEventData", ReplyAction="http://tempuri.org/IService1/fnInsertTicketEventDataResponse")]
        string fnInsertTicketEventData(string strAgentID, string strTicketID, string strTicketEventType, string strTicketCriticality, string strEventMessage, string strTicketLinkedTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnInsertTicketEventData", ReplyAction="http://tempuri.org/IService1/fnInsertTicketEventDataResponse")]
        System.Threading.Tasks.Task<string> fnInsertTicketEventDataAsync(string strAgentID, string strTicketID, string strTicketEventType, string strTicketCriticality, string strEventMessage, string strTicketLinkedTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnValidateLoginCredential", ReplyAction="http://tempuri.org/IService1/fnValidateLoginCredentialResponse")]
        string fnValidateLoginCredential(string JsonLoginRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fnValidateLoginCredential", ReplyAction="http://tempuri.org/IService1/fnValidateLoginCredentialResponse")]
        System.Threading.Tasks.Task<string> fnValidateLoginCredentialAsync(string JsonLoginRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basicEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Login(string userName, string password)
        {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password)
        {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public ServiceReference1.GlobalParameters getGlobalParameter()
        {
            return base.Channel.getGlobalParameter();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GlobalParameters> getGlobalParameterAsync()
        {
            return base.Channel.getGlobalParameterAsync();
        }
        
        public string fnGetAssetDetailsForAPI(string strAssetName)
        {
            return base.Channel.fnGetAssetDetailsForAPI(strAssetName);
        }
        
        public System.Threading.Tasks.Task<string> fnGetAssetDetailsForAPIAsync(string strAssetName)
        {
            return base.Channel.fnGetAssetDetailsForAPIAsync(strAssetName);
        }
        
        public int fnAddDeploymentJSONData(ServiceReference1.DeploymentJSONData DepJSONData)
        {
            return base.Channel.fnAddDeploymentJSONData(DepJSONData);
        }
        
        public System.Threading.Tasks.Task<int> fnAddDeploymentJSONDataAsync(ServiceReference1.DeploymentJSONData DepJSONData)
        {
            return base.Channel.fnAddDeploymentJSONDataAsync(DepJSONData);
        }
        
        public string fnGetAgentTicketManageData(string strAgentID)
        {
            return base.Channel.fnGetAgentTicketManageData(strAgentID);
        }
        
        public System.Threading.Tasks.Task<string> fnGetAgentTicketManageDataAsync(string strAgentID)
        {
            return base.Channel.fnGetAgentTicketManageDataAsync(strAgentID);
        }
        
        public string fnGetTicektDetailsData(string strTicketID)
        {
            return base.Channel.fnGetTicektDetailsData(strTicketID);
        }
        
        public System.Threading.Tasks.Task<string> fnGetTicektDetailsDataAsync(string strTicketID)
        {
            return base.Channel.fnGetTicektDetailsDataAsync(strTicketID);
        }
        
        public string fnInsertTicketEventData(string strAgentID, string strTicketID, string strTicketEventType, string strTicketCriticality, string strEventMessage, string strTicketLinkedTo)
        {
            return base.Channel.fnInsertTicketEventData(strAgentID, strTicketID, strTicketEventType, strTicketCriticality, strEventMessage, strTicketLinkedTo);
        }
        
        public System.Threading.Tasks.Task<string> fnInsertTicketEventDataAsync(string strAgentID, string strTicketID, string strTicketEventType, string strTicketCriticality, string strEventMessage, string strTicketLinkedTo)
        {
            return base.Channel.fnInsertTicketEventDataAsync(strAgentID, strTicketID, strTicketEventType, strTicketCriticality, strEventMessage, strTicketLinkedTo);
        }
        
        public string fnValidateLoginCredential(string JsonLoginRequest)
        {
            return base.Channel.fnValidateLoginCredential(JsonLoginRequest);
        }
        
        public System.Threading.Tasks.Task<string> fnValidateLoginCredentialAsync(string JsonLoginRequest)
        {
            return base.Channel.fnValidateLoginCredentialAsync(JsonLoginRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://euladox.rythium.com/TSService/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.basicEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.basicEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            basicEndPoint,
        }
    }
}
